### ISSUE TITLE
describe getpapers better

### ISSUE THREAD

**Issue by skasberger** [ContentMine/workshop-resources#22]
hat is getpapers exactly doing? describe it better. especially, what are the result (all the possibilities) and how is the relation with quickscrape.

**Comment by chreman** [comment]
from [#52](https://github.com/ContentMine/workshop-resources/issues/52):
- Lots of Qs about APIs/scrapers and links are not obvious without reading through all the software tutorial text. Could have a 'related links' at the top of the repo as well as the bottom or 'Are you looking for?' links.
- The VMs did not have scraper definitions so need to include these or give a clear instruction to download them with the following command: git clone https://github.com/ContentMine/journal-scrapers.git
- Trainer note: Need to be clear that while they're welcome to try their own material, they should follow all of the tutorials in order to use the papers for norma/AMI tutorials OR need bundles of files as input and output from each step in case it fails.
- Should flag in software tutorials that if they're using the vm they don't need to install the software and can use npm rather than sudo npm
- People wanted to work out how many papers they'd found before downloading them: getpapers --noexecute --query 'dinosaurs' etc
- If you get too many papers, try reducing the date range to a manageable number (see getpapers and EPMC query syntax). Our experience is ca 300 papers/min.
- To kill getpapers - Ctrl-C  (maybe twice)
